### ISSUE TITLE
Remove Placeholder library as depedency. 

### ISSUE THREAD

**Issue by NikoGrano** [grizzlyware/salmon-whmcs#1]

**Comment by mewejo** [comment]
@Niko9911 the plan is for Salmon to contain various helper methods, we're just trying to decide which warrant going in at the moment. Closing for now.

**Comment by NikoGrano** [comment]
@mewejo 

If you are interested https://gitlab.com/IronLions/whmcs-abstract

Ive been working on the abstraction library also...
